{
 "title": "Icinga2 (Prometheus)",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Icinga Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_num_services_critical\"}"
    }
   ]
  },
  {
   "title": "Services OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_num_services_ok\"}"
    }
   ]
  },
  {
   "title": "Hosts Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_num_hosts_down\"}"
    }
   ]
  },
  {
   "title": "Hosts Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_num_hosts_up\"}"
    }
   ]
  },
  {
   "title": "Icinga API HTTP Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_api_num_http_clients\"}"
    }
   ]
  },
  {
   "title": "Icinga2 Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_version_info\"}"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_avg_execution_time\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "{__name__=\"icinga2_min_execution_time\"}",
     "legendFormat": "min"
    },
    {
     "expr": "{__name__=\"icinga2_max_execution_time\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_avg_latency\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "{__name__=\"icinga2_min_latency\"}",
     "legendFormat": "min"
    },
    {
     "expr": "{__name__=\"icinga2_max_latency\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Active Checks Last 5 Minutes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_active_host_checks_5min\"}",
     "legendFormat": "Hosts"
    },
    {
     "expr": "{__name__=\"icinga2_active_service_checks_5min\"}",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "title": "Passive Checks Last 5 Minutes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_passive_host_checks_5min\"}",
     "legendFormat": "Hosts"
    },
    {
     "expr": "{__name__=\"icinga2_passive_service_checks_5min\"}",
     "legendFormat": "Services"
    }
   ]
  },
  { "title": "Hosts and Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Host State Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_num_hosts_in_downtime\"}",
     "legendFormat": "Downtime"
    },
    {
     "expr": "{__name__=\"icinga2_num_hosts_in_pending\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "{__name__=\"icinga2_num_hosts_unreachable\"}",
     "legendFormat": "Unreachable"
    },
    {
     "expr": "{__name__=\"icinga2_num_hosts_flapping\"}",
     "legendFormat": "Flapping"
    },
    {
     "expr": "{__name__=\"icinga2_num_hosts_problem\"}",
     "legendFormat": "Problem"
    }
   ]
  },
  {
   "title": "Service State Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{__name__=\"icinga2_num_services_in_downtime\"}",
     "legendFormat": "Downtime"
    },
    {
     "expr": "{__name__=\"icinga2_num_services_in_pending\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "{__name__=\"icinga2_num_services_unreachable\"}",
     "legendFormat": "Unreachable"
    },
    {
     "expr": "{__name__=\"icinga2_num_services_flapping\"}",
     "legendFormat": "Flapping"
    },
    {
     "expr": "{__name__=\"icinga2_num_services_problem\"}",
     "legendFormat": "Problem"
    }
   ]
  }
 ]
}