version: "2"
run:
  tests: false
linters:
  settings:
    revive:
     rules:
        - name: var-naming
          disabled: true
  default: all
  disable:
    - wsl_v5
    - dupl
    - godox
    - lll
    - exhaustruct
    - tagliatelle
    - forbidigo
    - wsl
    - depguard
    - err113
    - godot
    - mnd
    - nlreturn
    - cyclop
    - nolintlint
    - varnamelen
    - funlen
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/icinga/tls.go
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: 'internal/collector/cib.go'
        linters:
          - gocognit
          - gocyclo
          - maintidx
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
